<?php

namespace App\Filament\Resources\NutrientResource\Pages;

use App\Filament\Resources\NutrientResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListNutrients extends ListRecords
{
    protected static string $resource = NutrientResource::class;

    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()->where('type', 'nutrient'); // TODO: Change the autogenerated stub
    }
}
